//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkerPleaseIncludeGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("    }\r\n}\r\n")]
        public string FileSuffix {
            get {
                return ((string)(this["FileSuffix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Click;LongClick")]
        public string Events {
            get {
                return ((string)(this["Events"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("            x.{Property} = UseMe(x.{Property});")]
        public string PropertyTemplate {
            get {
                return ((string)(this["PropertyTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("       }\r\n                ")]
        public string TypeSuffix {
            get {
                return ((string)(this["TypeSuffix"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("            x.{Property} += null;")]
        public string EventTemplate {
            get {
                return ((string)(this["EventTemplate"]));
            }
            set {
                this["EventTemplate"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("        void Include{TypeWithoutDots}({Type} x)\r\n        {")]
        public string TypePrefix {
            get {
                return ((string)(this["TypePrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"using Android.Support.Design.Widget;
using Android.Support.V4.View;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;
using IRIS.ZustellerAppXamarin.Views;
using MvvmCross.Binding.Droid.Views;
using MvvmCross.Droid.Support.V7.RecyclerView;
using Post.Mobil.Barcode.Droid;

namespace LinkerPleaseIncludeGenerator
{
    public class LinkerPleaseIncludeMeGenerated
    {
        T UseMe<T>(T def) => def;
")]
        public string FilePrefix {
            get {
                return ((string)(this["FilePrefix"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  Visible
                  BackgroundDrawableFieldState
                  SelectedTabIndex
                  BackgroundDrawableBool
                  CommandBarClickCommand
                  OpenFlyoutMenuLongPress
                  SenderOnClick
                  MvxLinearLayout.Text
                  OpenFlyoutMenu
                  TextView.TextColor
                  ImageView.DrawableId
                  ImageView.DrawableName
                  ImageView.LocalImageUrl
                  ImageView.Tint
                  LayoutNotification.NotificationVisible
                  IrisNumberPicker.NumberPickerValue
                  BarcodeView.BackgroundDrawableByteArray
                ")]
        public string Ignore {
            get {
                return ((string)(this["Ignore"]));
            }
            set {
                this["Ignore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MvxBind")]
        public string attributeToSearch {
            get {
                return ((string)(this["attributeToSearch"]));
            }
            set {
                this["attributeToSearch"] = value;
            }
        }
    }
}
